### ISSUE TITLE
A6 not being measured with layout index 8

### ISSUE THREAD

**Issue by rbrenesh** [greyltc/solar-sim-software#11]
Whenever I specify device A6 to be measured I get the line (see attached picture as well).

`INFO: Skipping zero area pixel: A6`

I checked  the usr/etc/layouts.ini file and it seems to be correct though... (see second picture)

![Screenshot from 2019-03-13 14-37-52](https://user-images.githubusercontent.com/33428877/54471177-4b3fa800-478b-11e9-998f-cb0d9c87e287.png)

![Screenshot from 2019-03-13 14-39-18](https://user-images.githubusercontent.com/33428877/54471179-50045c00-478b-11e9-830d-11adef7e1189.png)

**Comment by greyltc** [comment]
Oh, that sounds like a bug! I'll see if I can recreate it here.

**Comment by greyltc** [comment]
Yep, I can recreate this

**Comment by greyltc** [comment]
@rbrenesh,
Should be all fixed by 5810841e5f474bfe0800ca181a1e33f4d78bcf42
and packaged up in v1.0.7
`yay -Sy python-mutovis-control`
