### ISSUE TITLE
we can't control an Abet or Newport solar sim

### ISSUE THREAD

**Issue by greyltc** [greyltc/solar-sim-software#6]

**Comment by greyltc** [comment]
@rbrenesh,
28ead5b should solve this
Now you should be able to use `--light-address env://FTDI_DEVICE` to read the solar sim connection protocol://address from an environment variable named `FTDI_DEVICE`. This will give an error if there is no `FTDI_DEVICE` environment variable

You can also use something like `--light-address ftdi://ftdi:232/1`

Rolled into release v1.0.6

This is very much untested, so please let me know if it does or doesn't work for you!

**Comment by rbrenesh** [comment]
Tested and working as expected!
