### ISSUE TITLE
the mppt's exploration region is too large

### ISSUE THREAD

**Issue by greyltc** [greyltc/solar-sim-software#8]
@rbrenesh
Creating this issue to capture previous email

**Comment by rbrenesh** [comment]
Adding a picture of 30s MPPT of a device for context. It seems like the lower end of the exploration is a bit too big. Reducing that should also make the exploration phase shorter as well.

![Screenshot from 2019-03-14 11-47-09](https://user-images.githubusercontent.com/33428877/54391637-ce71d880-467b-11e9-8ca0-b2236c5ab7b9.png)

**Comment by greyltc** [comment]
I'll make the size of the exploration region something that can be configured. I'm also working on adding a new mppt algorithm

**Comment by greyltc** [comment]
@rbrenesh,
03877e084ac815c0870b578ae4acdda4ceb71b60 should address this, it makes the size of the exploration region configurable (as well as the duration of the dwell phases, which were previously fixed at 10s).

It adds a new interface for configuring the max power point tracker with `--mppt-params` This is also how we will switch between different maximum power point tracking algorithms and configure them in the future, right now the only mppt available is `basic`. I imagine this configuration will become more complicated so I've made special documentation for it here: https://github.com/mutovis/control-software/blob/master/MPPT.md

The old mppt was equivalent to `--mppt-params basic://7:10` that means +/- 7 degrees of exploration and 10 second dwell periods. Now for example you can do `--mppt-params basic://3:10` which means you'll explore +/- 3 degrees around the max power point.

Here's +/- 7 degrees (the previous unconfigurable MPPT) for 37 seconds:
![Figure_1_7](https://user-images.githubusercontent.com/16778174/54725166-fd99b580-4b65-11e9-9f6a-37f9f3b7e81f.png)
and here's +/- 3 degrees with `--mppt-params basic://3:10` also for 37 seconds:
![Figure_1_3](https://user-images.githubusercontent.com/16778174/54725187-13a77600-4b66-11e9-898d-1bfea96b0b83.png)
Don't mind the sloped power output on these graphs, that's just the battery dying on the flashlight I use to illuminate & test at my desk! ;-)
 
I think this should give you what you were looking for! If not, feel free to just comment here to let me know what I've missed.

I've released this in v1.0.8, so as usual
`yay -Sy python-mutovis-control`
